routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


Route::group(['prefix' => 'api'], function () {
    \JoseMiguelMelo\Newsletter\Models\Newsletter::routes();

    Route::get('application/{id}/subscribers', ['uses' => 'ApplicationsController@subscribers']);
    Route::resource('application', 'ApplicationsController');
    Route::post('application/send_all', ['uses' => 'NewsletterController@sendToAll']);

    Route::get('application/{id}/delivery_log', ['uses' => 'FailuresController@deliveryLog']);

    Route::post('application/report', ['uses' => 'ReportController@retrieveInformation']);
    Route::post('application/update_view', ['uses' => 'ApplicationsController@updateNewsletter']);

    Route::post('newsletter/send/{email}', ['uses' => 'NewsletterController@sendToEmail']);
    Route::post('newsletter/activate/{email}', ['uses' => 'NewsletterController@activate']);
});



Auth::routes();

Route::resource('application', 'ApplicationsController');

Route::get('newsletters/subscribe', function () {
    return view('subscribe');
});

Route::get('newsletter_page', ['uses' => 'ApplicationsController@newsletterPage']);

Route::get('/', [
    'as' => 'home', 'uses' => function () {
        if(\Illuminate\Support\Facades\Auth::check())
            return response()->redirectTo('/app/');

        return response()->view('home');
    }]);

Route::get('/{catchall?}', function () {
    return response()->view('home');
})->where('catchall', '(.*)')->middleware('auth');

app/Models/Application.php
<?php

namespace Newsltr\Models;

use Illuminate\Database\Eloquent\Model;


class Application extends Model
{
    //
    protected $fillable = [
        'name', 'email', 'auto_send', 'default_frequency', 'api_token'
    ];

    public function user()
    {
        return $this->belongsTo('Newsltr\Models\User', 'user_id');
    }

    public function newsletters()
    {
        return $this->hasMany('\JoseMiguelMelo\Newsletter\Models\Newsletter', 'application_id');
    }


    public function getDefaultFrequencyAttribute($value)
    {
        switch ($value)
        {
            case 0: return 'daily';
            case 1: return 'weekly';
            case 2: return 'monthly';
            default: return 'daily';
        }
    }
    public function setDefaultFrequencyAttribute($value)
    {
        switch ($value)
        {
            case 'daily':
                $this->attributes['default_frequency'] = 0;
                break;
            case 'weekly':
                $this->attributes['default_frequency'] = 1;
                break;
            case 'monthly':
                $this->attributes['default_frequency'] = 2;
                break;
            default:
                $this->attributes['default_frequency'] = 0;
                break;
        }
    }
}

app/Http/Controllers/ApplicationsController.php
<?php

namespace Newsltr\Http\Controllers;

use Newsltr\Models\Application;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ApplicationsController extends Controller
{
    public function index()
    {
        if ( ! Auth::check())
            return response()->json(['error' => true, 'msg' => 'Please login to access']);

        return response()->json(['error' => false, 'applications' => Auth::user()->applications]);
    }

    public function show($id)
    {
        \Log::info("Application id = " . $id);
        if ( ! Auth::check())
            return response()->json(['error' => true, 'msg' => 'Please login to access']);

        return response()->json(
            [
                'error'       => false,
                'application' => Auth::user()->applications()->where('id', $id)->first(),
            ]);
    }

    public function create()
    {
        return view('applications.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name'  => 'required|unique:applications,name|min:3',
            'email' => 'required|unique:applications,email|email',
        ]);

        $defaultFrequency = (($request->has('auto_send') == true) ? $request->get('frequency') : -1);

        $application = Auth::user()->applications()->create(
            [
                'name'              => $request->get('name'),
                'email'             => $request->get('email'),
                'auto_send'         => $request->has('auto_send'),
                'default_frequency' => $defaultFrequency,
                'api_token'         => str_random(30),
            ]);

        if ( ! $request->ajax())
            return redirect()->route('home')->with('confirmationMessage', 'Application added successfully');

        return response()->json(
            [
                'error'       => false,
                'msg'         => 'Application added successfully.',
                'application' => $application,
            ]);
    }

    public function update(Request $request, $applicationId)
    {
        \Log::info($request->all());
        $application = Auth::user()->applications()->where('id', $applicationId)->first();

        if ( ! $application)
            return response()->json(
                [
                    'error' => true,
                    'msg'   => 'Application not found.',
                ]);

        $this->validate($request, [
            'name'              => 'required|min:3|unique:applications,name,' . $application->id,
            'email'             => 'required|email|unique:applications,email,' . $application->id,
            'auto_send'         => 'required|boolean',
            'default_frequency' => 'in:"daily","weekly","monthly"',
        ]);

        $application->name = $request->has('name') ? $request->get('name') : $application->name;
        $application->email = $request->has('email') ? $request->get('email') : $application->email;
        $application->auto_send = $request->has('auto_send') ? $request->get('auto_send') : $application->auto_send;
        $application->default_frequency = $request->has('default_frequency') ? $request->get('default_frequency') : $application->default_frequency;

        $application->save();

        return response()->json(
            [
                'error'       => false,
                'msg'         => 'Application updated successfully.',
                'application' => $application,
            ]);
    }

    public function destroy($application)
    {
        if (Application::destroy($application))
            return response()->json(
                [
                    'error' => false,
                    'msg'   => 'Application deleted successfully.',
                ]);

        // Application not deleted.
        return response()->json(
            [
                'error' => true,
                'msg'   => 'Application could not be deleted.',
            ]);
    }

    public function updateNewsletter(Request $request)
    {
        if ( ! $request->has('application_id') || ! $request->has('view'))
            return response()->json(['error' => true, 'msg' => 'Missing param.']);

        $input = $request->all();

        $application = Application::find($input['application_id']);
        if ( ! $application)
            return response()->json(['error' => true, 'msg' => 'Application not found.']);

        $application->newsletter_view = $input['view'];
        $application->save();

        return response()->json(['error' => false, 'msg' => 'View updated successfully.']);
    }


    /**
     * @param $applicationId Application id sent on url
     * @return \Illuminate\Http\JsonResponse List of subscribers of application with id $applicationId
     */
    public function subscribers($applicationId)
    {
        $subscribers = \Newsltr\Models\Application::find($applicationId)->newsletters;
        return response()->json($subscribers);
    }


    public function newsletterPage(Request $request)
    {
        $website = $request->get('website');
        if (filter_var($website, FILTER_VALIDATE_URL)) {
            $webPage = file_get_contents($website);
            if ( ! $this->is_utf8($webPage))
                $webPage = utf8_decode($webPage);
            return response()->json(['error' => false, 'html' => $webPage]);
        }
        return response()->json(['error' => true, 'msg' => 'Not valid website']);
    }


    private function is_utf8($string)
    {
        return (mb_detect_encoding($string, 'UTF-8', true) == 'UTF-8');
    }
}

resources/views/applications/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">New Application</div>

                    <div class="panel-body">
                        @include('errors.form-errors')

                        <form method="post" action="{{ route('application.store') }}">
                            <input type="text" value="{{ csrf_token() }}" name="_token" hidden/>
                            <div class="form-group">
                                <label for="name">Name:</label>
                                <input type="text" class="form-control" id="name" name="name"
                                       placeholder="Your application name">
                            </div>

                            <div class="form-group">
                                <label for="email">Email:</label>
                                <input type="email" class="form-control" id="email" name="email"
                                       placeholder="Email used to send newsletter">
                            </div>

                            <div class="form-group">
                                <label>Auto Send Newsletter</label>
                                <div class="material-switch pull-right">
                                    <input id="auto-send" name="auto-send" type="checkbox" value="true"/>
                                    <label for="auto-send" class="label-success"></label>
                                </div>
                            </div>

                            <div class="form-group" id="frequency-selection" hidden>
                                <label>Frequency</label>
                                <select class="form-control" name="frequency">
                                    <option value="daily">Daily</option>
                                    <option value="weekly">Weekly</option>
                                    <option value="monthly">Monthly</option>
                                </select>
                            </div>

                            <button type="submit" class="btn btn-primary">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        document.getElementById("auto-send").onclick = function () {
            if (this.checked) {
                document.getElementById("frequency-selection").style.display = 'block';
            } else {
                document.getElementById("frequency-selection").style.display = 'none';
            }
        };
    </script>
@endsection